name: pair3
services:
  pair3:
    build:
      context: .
      dockerfile: Dockerfile1
      target: development
    image: template:0.1.1
    command: [ "sh","-c","uv run ao.py" ]
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
